name: test
on:
  - push
  - pull_request
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        node-version:
          - 14.17.0
          - 17.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Run tests
        run: npm test
        env:
          AWS_KEY: ${{ secrets.AWS_KEY }}
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
          AWS_ENDPOINT: https://sgp1.digitaloceanspaces.com
          AWS_BUCKET: testing-flydrive
  windows:
    runs-on: windows-latest
    needs: linux
    strategy:
      max-parallel: 1
      matrix:
        node-version:
          - 14.17.0
          - 17.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Run tests
        run: npm test
        env:
          AWS_KEY: ${{ secrets.AWS_KEY }}
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
          AWS_ENDPOINT: https://sgp1.digitaloceanspaces.com
          AWS_BUCKET: testing-flydrive
